modLoader = "javafml"
loaderVersion = "[4,)"
license = "${mod_license}"
issueTrackerURL = "${mod_issues}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "${mod_homepage}"
authors = "${mod_authors}"
description = '''${mod_description}'''
displayTest = "MATCH_VERSION"

[[mixins]]
config = "cobblemon_kinetics.mixins.json"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.219,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "create"
type = "required"
versionRange = "[${create_version},6.1.0)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "cobblemon"
type = "required"
versionRange = "[${cobblemon_version},1.8.0)"
ordering = "AFTER"
side = "BOTH"
